#
- name: "mass added linux host on zabbix server"
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    zabbix_config_path: "etc/zabbix/zabbix_agentd.conf"
    zabbix_config: zabbix_agentd.conf
    zabbix_service: zabbix-agent.service
    repo_file: sources_ansible+zabbix.list
  tasks:
# repo
    - name: added local repo
      copy:
        force: yes
        src: ./{{ repo_file }}
        dest: /etc/apt/{{ repo_file }}
        owner: root
        group: root
        mode: '0644'
      when:
        - ansible_distribution.find('Astra Linux') != -1
# zabbix packege and config
    - name: update apt cache
      apt:
        update_cache: yes
    - name: apt search
      shell: apt-get install -s zabbix-agent
      register: try_apt_search
    - name: show search packet on local repo
      debug:
        msg: "{{try_apt_search.failed}}"

    - name: install package zabbix-agent
      apt:
        update_cache: no
        name: zabbix-agent
        state: "latest"

    - name: "copy {{ zabbix_config }} to linux host"
      copy:
        force: true
        src: ./{{ zabbix_config }}
        dest: /{{ zabbix_config_path }}
        owner: root
        group: root
        mode: '0644'

# restart service
    - name: "restart {{ zabbix_service }}"
      service:
        name: "{{ zabbix_service }}"
        state: restarted
